import type { ShapeDef } from "./shape.ts";
import type { TessellationDef } from "./tessellation.ts";

/** A single cell. Tiles the plane on the unit lattice. The baseline sanity case. */
export const UNIT_SQUARE: TessellationDef = {
  name: "unit-square",
  shape: { name: "square-1", cells: [{ x: 0, y: 0 }] },
  basis1: { x: 1, y: 0 },
  basis2: { x: 0, y: 1 },
  placements: [{ offset: { x: 0, y: 0 }, orientation: 0 }],
};

/** An L-tromino: the 2x2 square with one corner removed. */
export const L_TROMINO: ShapeDef = {
  name: "L-tromino",
  cells: [
    { x: 0, y: 0 },
    { x: 1, y: 0 },
    { x: 0, y: 1 },
  ],
};

/**
 * L-trominoes paired into 2x3 bricks. Two orientations (ID and R180) sit in one
 * fundamental cell of the rectangular lattice generated by (2, 0) and (0, 3).
 */
export const L_TROMINO_BRICK: TessellationDef = {
  name: "L-tromino-brick",
  shape: L_TROMINO,
  basis1: { x: 2, y: 0 },
  basis2: { x: 0, y: 3 },
  placements: [
    { offset: { x: 0, y: 0 }, orientation: 0 }, // ID
    { offset: { x: 1, y: 2 }, orientation: 2 }, // R180
  ],
};
