import { applyD4, composeD4, D4_NAMES, type D4 } from "../core/d4.ts";
import { addVec, keyVec, subVec, type Vec2 } from "../core/vec2.ts";
import { transformedCells } from "../model/shape.ts";
import {
  reduceModLattice,
  transformTessellation,
  type TessellationDef,
} from "../model/tessellation.ts";
import { isLatticeVector } from "./validate.ts";

/**
 * The symmetry group of a tessellation, and the classification of its tiles.
 *
 * A tessellation's **symmetry group** G is every isometry that maps the tiling
 * onto itself. Its **translation subgroup** L* (a sublattice of Z², possibly
 * bigger than the basis the tiling was described with) is the set of pure
 * translations in G. The quotient G / L* is a subgroup of D4, the tile's
 * point symmetries.
 *
 * Tiles fall into **orbits** under G: two tiles are symmetry-equivalent (the
 * same "shape tessellation" in the game's terms) iff some g in G carries one to
 * the other. Within an orbit, the class of a tile is the D4 part of a symmetry
 * carrying the reference tile to it. That is the label the renderer colours by.
 */

export interface TileInstance {
  readonly placement: number;
  readonly m: number;
  readonly n: number;
}

interface TileInfo {
  readonly placement: number;
  readonly orientation: D4;
  readonly base: Vec2;
}

interface TorusData {
  readonly basis1: Vec2;
  readonly basis2: Vec2;
  /** Canonical representatives of Z² / L, one per coset. */
  readonly residues: Vec2[];
  /** Tile covering each residue cell. */
  readonly info: Map<string, TileInfo>;
}

/** The tile instance covering a cell, or undefined if the tiling misses it. */
export function tileAt(def: TessellationDef, cell: Vec2): TileInstance | undefined {
  const { basis1, basis2 } = def;
  for (let p = 0; p < def.placements.length; p++) {
    const cells = transformedCells(def.shape, def.placements[p].orientation);
    const offset = def.placements[p].offset;
    for (const c of cells) {
      const t = subVec(subVec(cell, c), offset);
      const coords = latticeCoordsOrNull(t, basis1, basis2);
      if (!coords) continue;
      const m = Math.round(coords.t1);
      const n = Math.round(coords.t2);
      if (Math.abs(coords.t1 - m) < 1e-6 && Math.abs(coords.t2 - n) < 1e-6) {
        return { placement: p, m, n };
      }
    }
  }
  return undefined;
}

function latticeCoordsOrNull(
  u: Vec2,
  basis1: Vec2,
  basis2: Vec2,
): { t1: number; t2: number } | null {
  const det = basis1.x * basis2.y - basis1.y * basis2.x;
  if (det === 0) return null;
  return {
    t1: (basis2.y * u.x - basis2.x * u.y) / det,
    t2: (basis1.x * u.y - basis1.y * u.x) / det,
  };
}

function instanceBase(def: TessellationDef, instance: TileInstance): Vec2 {
  const offset = def.placements[instance.placement].offset;
  return addVec(
    offset,
    addVec(
      { x: def.basis1.x * instance.m, y: def.basis1.y * instance.m },
      { x: def.basis2.x * instance.n, y: def.basis2.y * instance.n },
    ),
  );
}

/** Canonical representatives of Z²/L plus the tile covering each one. */
function torusData(def: TessellationDef, basis1: Vec2, basis2: Vec2): TorusData {
  // The Hermite basis (a, 0), (b, c) gives a fundamental domain that is the
  // rectangle [0, a) x [0, c), so those a*c points are exactly one
  // representative per coset. Much cheaper than scanning a bounding box.
  const [h1, h2] = hermiteBasis([basis1, basis2]);
  const info = new Map<string, TileInfo>();
  const residues: Vec2[] = [];
  for (let y = 0; y < h2.y; y++) {
    for (let x = 0; x < h1.x; x++) {
      const rep = reduceModLattice({ x, y }, basis1, basis2);
      const key = keyVec(rep);
      if (info.has(key)) continue;
      const instance = tileAt(def, rep);
      if (!instance) continue;
      info.set(key, {
        placement: instance.placement,
        orientation: def.placements[instance.placement].orientation,
        base: instanceBase(def, instance),
      });
      residues.push(rep);
    }
  }
  return { basis1, basis2, residues, info };
}

/** A basis of the lattice generated by `gens` (Hermite normal form). */
function hermiteBasis(gens: readonly Vec2[]): [Vec2, Vec2] {
  // c = gcd of the y-coordinates, with `w` an integer combination of the
  // generators whose y-coordinate is exactly c.
  let c = 0;
  let w: Vec2 = { x: 0, y: 0 };
  for (const g of gens) {
    if (g.y === 0) continue;
    const positive = g.y < 0 ? { x: -g.x, y: -g.y } : { x: g.x, y: g.y };
    if (c === 0) {
      c = positive.y;
      w = positive;
      continue;
    }
    const divisor = gcd(c, positive.y);
    const [s, t] = extGcd(c, positive.y);
    w = { x: s * w.x + t * positive.x, y: divisor };
    c = divisor;
  }
  if (c === 0) throw new Error("lattice has rank < 2");

  // Elements with y = 0 have x-coordinates forming aZ; collect candidates.
  let a = 0;
  for (const g of gens) {
    if (g.y === 0) {
      a = gcd(a, g.x);
      continue;
    }
    a = gcd(a, (g.y / c) * w.x - g.x);
  }
  if (a === 0) throw new Error("lattice has rank < 2");
  const b = ((w.x % a) + a) % a;
  return [
    { x: a, y: 0 },
    { x: b, y: c },
  ];
}

function gcd(a: number, b: number): number {
  a = Math.abs(a);
  b = Math.abs(b);
  while (b) [a, b] = [b, a % b];
  return a;
}

function extGcd(a: number, b: number): [number, number] {
  if (b === 0) return [1, 0];
  const [x, y] = extGcd(b, a % b);
  return [y, x - Math.floor(a / b) * y];
}

export interface TranslationLattice {
  readonly basis1: Vec2;
  readonly basis2: Vec2;
  /** Non-identity translations (mod the given basis) that preserve the tiling. */
  readonly extraTranslations: Vec2[];
}

/** The full translation subgroup of the symmetry group, as a reduced basis. */
export function translationLattice(def: TessellationDef): TranslationLattice {
  const data = torusData(def, def.basis1, def.basis2);
  const extraTranslations = data.residues.filter(
    (v) => (v.x !== 0 || v.y !== 0) && preservesTranslation(data, v),
  );
  const gens = [def.basis1, def.basis2, ...extraTranslations];
  const [basis1, basis2] = hermiteBasis(gens);
  return { basis1, basis2, extraTranslations };
}

function preservesTranslation(data: TorusData, v: Vec2): boolean {
  for (const r of data.residues) {
    const a = data.info.get(keyVec(r));
    const b = data.info.get(
      keyVec(reduceModLattice(addVec(r, v), data.basis1, data.basis2)),
    );
    if (!a || !b) return false;
    if (a.orientation !== b.orientation) return false;
    if (!isLatticeVector(subVec(subVec(b.base, a.base), v), data.basis1, data.basis2)) {
      return false;
    }
  }
  return true;
}

export interface PointSymmetry {
  readonly g: D4;
  readonly t: Vec2;
  /** Tile that the reference tile (covering the origin) maps to. */
  readonly target: Vec2;
}

/** All non-translation symmetries: one representative `(g, t)` per D4 element. */
export function pointSymmetries(def: TessellationDef): PointSymmetry[] {
  const { basis1, basis2 } = translationLattice(def);
  const data = torusData(def, basis1, basis2);
  const reference = data.info.get("0,0");
  if (!reference) return [];

  const tiles = uniqueTiles(data, basis1, basis2);
  const result: PointSymmetry[] = [];
  for (let gi = 0; gi < D4_NAMES.length; gi++) {
    const g = gi as D4;
    // The operation must normalise the translation lattice.
    if (
      !isLatticeVector(applyD4(g, basis1), basis1, basis2) ||
      !isLatticeVector(applyD4(g, basis2), basis1, basis2)
    ) {
      continue;
    }
    for (const target of tiles) {
      if (target.orientation !== composeD4(reference.orientation, g)) continue;
      const t = subVec(target.base, applyD4(g, reference.base));
      if (preservesIsometry(data, g, t)) {
        result.push({ g, t, target: { ...target.base } });
        break;
      }
    }
  }
  return result;
}

function preservesIsometry(data: TorusData, g: D4, t: Vec2): boolean {
  for (const r of data.residues) {
    const a = data.info.get(keyVec(r));
    if (!a) return false;
    const moved = addVec(applyD4(g, r), t);
    const b = data.info.get(
      keyVec(reduceModLattice(moved, data.basis1, data.basis2)),
    );
    if (!b) return false;
    if (b.orientation !== composeD4(a.orientation, g)) return false;
    const image = addVec(applyD4(g, a.base), t);
    if (!isLatticeVector(subVec(b.base, image), data.basis1, data.basis2)) {
      return false;
    }
  }
  return true;
}

function uniqueTiles(
  data: TorusData,
  basis1: Vec2,
  basis2: Vec2,
): TileInfo[] {
  const seen = new Map<string, TileInfo>();
  for (const tile of data.info.values()) {
    const key = `${tile.orientation}:${keyVec(reduceModLattice(tile.base, basis1, basis2))}`;
    if (!seen.has(key)) seen.set(key, tile);
  }
  return [...seen.values()];
}

export interface TileClass {
  readonly orbit: number;
  readonly label: D4;
}

export interface SymmetryAnalysis {
  readonly basis1: Vec2;
  readonly basis2: Vec2;
  readonly pointSymmetries: PointSymmetry[];
  readonly orbitCount: number;
  /** Class of the tile instance covering `cell` (or undefined if none). */
  classAt(cell: Vec2): TileClass | undefined;
  /** Palette slot (0..15) for a tile, combining orbit and D4 label. */
  slotAt(cell: Vec2): number;
  /** Palette slot for a tile by its orientation and base point. */
  slotFor(orientation: D4, base: Vec2): number;
}

/**
 * Groups the tiles into orbits under the full symmetry group and labels each by
 * the D4 part of a symmetry carrying the reference tile to it.
 */
export function analyzeSymmetry(def: TessellationDef): SymmetryAnalysis {
  const { basis1, basis2 } = translationLattice(def);
  const data = torusData(def, basis1, basis2);
  const point = pointSymmetries(def);

  // Node key for a tile: orientation plus its base modulo the translation lattice.
  const nodeKey = (orientation: D4, base: Vec2): string =>
    `${orientation}:${keyVec(reduceModLattice(base, basis1, basis2))}`;
  const referenceKey = nodeKey(
    data.info.get("0,0")?.orientation ?? 0,
    data.info.get("0,0")?.base ?? { x: 0, y: 0 },
  );

  // BFS over the point symmetries to find reachable tiles and their labels.
  const label = new Map<string, D4>();
  label.set(referenceKey, 0);
  const queue: { key: string; orientation: D4; base: Vec2 }[] = [];
  const refTile = uniqueTiles(data, basis1, basis2).find(
    (tile) => nodeKey(tile.orientation, tile.base) === referenceKey,
  );
  if (refTile) {
    queue.push({
      key: referenceKey,
      orientation: refTile.orientation,
      base: refTile.base,
    });
  }
  while (queue.length > 0) {
    const current = queue.shift() as { key: string; orientation: D4; base: Vec2 };
    const currentLabel = label.get(current.key) as D4;
    for (const { g, t } of point) {
      const image = addVec(applyD4(g, current.base), t);
      const movedKey = nodeKey(composeD4(current.orientation, g), image);
      if (label.has(movedKey)) continue;
      const next = composeD4(currentLabel, g);
      label.set(movedKey, next);
      const tile = uniqueTiles(data, basis1, basis2).find(
        (candidate) => nodeKey(candidate.orientation, candidate.base) === movedKey,
      );
      queue.push({
        key: movedKey,
        orientation: tile?.orientation ?? composeD4(current.orientation, g),
        base: tile?.base ?? image,
      });
    }
  }

  // Orbits: connected components of the point-symmetry action on all tiles.
  const allTiles = uniqueTiles(data, basis1, basis2);
  const orbitOf = new Map<string, number>();
  let orbitCount = 0;
  for (const tile of allTiles) {
    const startKey = nodeKey(tile.orientation, tile.base);
    if (orbitOf.has(startKey)) continue;
    const orbit = orbitCount++;
    const stack = [tile];
    orbitOf.set(startKey, orbit);
    while (stack.length > 0) {
      const current = stack.pop() as TileInfo;
      for (const { g, t } of point) {
        const image = addVec(applyD4(g, current.base), t);
        const key = nodeKey(composeD4(current.orientation, g), image);
        if (orbitOf.has(key)) continue;
        orbitOf.set(key, orbit);
        const match = allTiles.find(
          (candidate) => nodeKey(candidate.orientation, candidate.base) === key,
        );
        if (match) stack.push(match);
      }
    }
  }

  const classForTile = (tile: TileInfo): TileClass => ({
    orbit: orbitOf.get(nodeKey(tile.orientation, tile.base)) ?? 0,
    label: label.get(nodeKey(tile.orientation, tile.base)) ?? 0,
  });

  const classAt = (cell: Vec2): TileClass | undefined => {
    const rep = reduceModLattice(cell, basis1, basis2);
    const tile = data.info.get(keyVec(rep));
    return tile ? classForTile(tile) : undefined;
  };

  const slotOfKey = (key: string): number => {
    // Single-orbit tilings get the 8 D4 tones; further orbits reuse the palette
    // with a shifted base.
    return ((label.get(key) ?? 0) + 8 * (orbitOf.get(key) ?? 0)) % 16;
  };

  return {
    basis1,
    basis2,
    pointSymmetries: point,
    orbitCount,
    classAt,
    slotAt: (cell: Vec2): number => {
      const tile = data.info.get(
        keyVec(reduceModLattice(cell, basis1, basis2)),
      );
      return tile ? slotOfKey(nodeKey(tile.orientation, tile.base)) : 0;
    },
    slotFor: (orientation: D4, base: Vec2): number =>
      slotOfKey(nodeKey(orientation, base)),
  };
}

/**
 * A canonical signature for a tessellation, invariant under translation, the
 * symmetries of the square, and any extra translational symmetry of the tiling.
 *
 * It is built on the **primitive translation lattice**: the plane modulo that
 * lattice is partitioned into tiles, and the partition (with orientations,
 * minimised over the choice of origin) is the signature. Describing the same
 * tiling with a larger supercell therefore collapses to the same signature.
 */
export function canonicalSignature(def: TessellationDef): string {
  let best: string | undefined;
  for (let gi = 0; gi < D4_NAMES.length; gi++) {
    const g = gi as D4;
    const transformed = transformTessellation(def, g);
    // Recompute the transformed tiling's own translation lattice: rotating the
    // basis directly can skew it, which would change `reduceModLattice`'s
    // coset representatives and produce a different signature for the same
    // tiling.
    const lattice = translationLattice(transformed);
    const signature = torusSignature(
      transformed,
      lattice.basis1,
      lattice.basis2,
    );
    if (best === undefined || signature < best) best = signature;
  }
  return best as string;
}

function torusSignature(
  def: TessellationDef,
  basis1: Vec2,
  basis2: Vec2,
): string {
  const data = torusData(def, basis1, basis2);
  // Group residues by the tile that covers them.
  const tiles = new Map<string, { orientation: D4; residues: Vec2[] }>();
  for (const residue of data.residues) {
    const tile = data.info.get(keyVec(residue));
    if (!tile) continue;
    const key = `${tile.orientation}:${keyVec(reduceModLattice(tile.base, basis1, basis2))}`;
    let entry = tiles.get(key);
    if (!entry) {
      entry = { orientation: tile.orientation, residues: [] };
      tiles.set(key, entry);
    }
    entry.residues.push(residue);
  }

  // Minimise over the choice of origin (gauge) within the lattice.
  let best: string | undefined;
  for (const shift of data.residues) {
    const encoded = [...tiles.values()]
      .map((tile) => {
        const cells = tile.residues
          .map((r) => reduceModLattice(addVec(r, shift), basis1, basis2))
          .map(keyVec)
          .sort()
          .join("|");
        return `${tile.orientation}:${cells}`;
      })
      .sort()
      .join(";");
    if (best === undefined || encoded < best) best = encoded;
  }
  return best as string;
}

export function sameTessellation(a: TessellationDef, b: TessellationDef): boolean {
  return canonicalSignature(a) === canonicalSignature(b);
}
